# Site
name: 'Coded Stories'
description: 'Coded Stories is my experiments and things I figured out that I want to share with you'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/blog'
disqus: 'blog'
email: 'judeosby@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    jude:
      name:           Jude Osbert K
      site:           judeosbert.github.io
      avatar:         assets/images/njan.jpg
      bio:            "Hi, I am Jude, the author of CodedStories, I am hoping to share my view of coding and understand things better."
      email:          judeosby@gmail.com

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: jude
      avatar: http://judeosbert.github.io/images/njan.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]